starts = ['TACGGCCCCAGAATTCAAAA']
stops = ['TCGGGTGGGCCTTTCTGC']
oligo_path = '/Users/cambray/Dropbox/BIOFAB/Wet Lab/Data/Sequencing/sequencing_oligos.csv'
mapping_path = ''
ref_path = '/Users/cambray/Dropbox/BIOFAB/Wet Lab/Data/pFAB-pOUT/listing.csv'
trace_path = '/Users/cambray/Downloads/031711_GC-1'
parse_phrase = '(\d+)'
output_folder = '/Users/cambray/Downloads/031711_GC-1'
cap3_path = '/applications/Cap3'