package org.clothocad.hibernate.data;
// Generated Jun 18, 2010 6:49:47 PM by Hibernate Tools 3.2.1.GA

/**
 * CompositeXref generated by hbm2java
 */
public class CompositeXref implements java.io.Serializable {

    private String idComposite;
    private PartTable partTableByParentPart;
    private PartTable partTableByChildPart;
    private Integer position;

    public CompositeXref () {
    }

    public CompositeXref ( String idComposite ) {
        this.idComposite = idComposite;
    }

    public CompositeXref ( String idComposite, PartTable partTableByParentPart, PartTable partTableByChildPart, Integer position ) {
        this.idComposite = idComposite;
        this.partTableByParentPart = partTableByParentPart;
        this.partTableByChildPart = partTableByChildPart;
        this.position = position;
    }

    public String getIdComposite () {
        return this.idComposite;
    }

    public void setIdComposite ( String idComposite ) {
        this.idComposite = idComposite;
    }

    public PartTable getPartTableByParentPart () {
        return this.partTableByParentPart;
    }

    public void setPartTableByParentPart ( PartTable partTableByParentPart ) {
        this.partTableByParentPart = partTableByParentPart;
    }

    public PartTable getPartTableByChildPart () {
        return this.partTableByChildPart;
    }

    public void setPartTableByChildPart ( PartTable partTableByChildPart ) {
        this.partTableByChildPart = partTableByChildPart;
    }

    public Integer getPosition () {
        return this.position;
    }

    public void setPosition ( Integer position ) {
        this.position = position;
    }

}


