/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.clothocore.api.data.FlexField;
import org.clothocore.api.data.FlexField.FlexFieldDatum;
import org.clothocore.api.data.ObjBase;
import org.clothocore.api.data.ObjBase.ObjBaseDatum;
import org.clothocore.api.data.ObjType;
import org.clothocad.hibernate.hibernateDatum;

/**
 * FlexfieldTable generated by hbm2java
 */
public class FlexfieldTable implements java.io.Serializable, hibernateDatum {

    public static ObjType getType( Enum field ) {
        throw new UnsupportedOperationException( "Not yet implemented" );
    }

    public FlexfieldTable( FlexField f ) {
        this.idFlexfield = f.getUUID();
        this.name = f.getName();
        this.dateCreated = f.getDateCreated();
        this.lastModified = f.getLastModified();
        this.pluginId = f.getPluginId();
        //TODO: Fix flex field data xrefs
    }

    @Override
    public ObjBase getObject() {
        FlexField.FlexFieldDatum d = (FlexFieldDatum) getObjBaseDatum();
        FlexField ff = new FlexField( d );
        return ff;
    }

    @Override
    public void runSecondaryProcessing(ObjBase obj) {
    }

    @Override
    public boolean needsSecondaryProcessing() {
        return false;
    }
    

    @Override
    public ObjBaseDatum getObjBaseDatum() {
        FlexField.FlexFieldDatum d = new FlexField.FlexFieldDatum();
        d.uuid = idFlexfield;
        d.name = name;
        d.dateCreated = dateCreated;
        d.lastModified = lastModified;
        d._pluginId = pluginId;
        return d;
    }

    @Override
    public String getUUID() {
        return idFlexfield;
    }

    public static String translate( Enum field ) {
        if ( field.getDeclaringClass() != FlexField.Fields.class ) {
            return null;
        }

        FlexField.Fields f = (FlexField.Fields) field;

        switch ( f ) {
            case NAME:
                return "name";
            case DATE_CREATED:
                return "dateCreated";
            case LAST_MODIFIED:
                return "lastModifed";
            default:
                return null;
        }
    }
    /***** AUTO-GENERATED CODE *****/
    private String idFlexfield;
    private String pluginId;
    private String name;
    private Date dateCreated;
    private Date lastModified;
    private Set flexfieldDataXrefs = new HashSet( 0 );

    public FlexfieldTable() {
    }

    public FlexfieldTable( String idFlexfield ) {
        this.idFlexfield = idFlexfield;
    }

    public FlexfieldTable( String idFlexfield, String pluginId, String name, Date dateCreated, Date lastModified, Set flexfieldDataXrefs ) {
        this.idFlexfield = idFlexfield;
        this.pluginId = pluginId;
        this.name = name;
        this.dateCreated = dateCreated;
        this.lastModified = lastModified;
        this.flexfieldDataXrefs = flexfieldDataXrefs;
    }

    public String getIdFlexfield() {
        return this.idFlexfield;
    }

    public void setIdFlexfield( String idFlexfield ) {
        this.idFlexfield = idFlexfield;
    }

    public String getPluginId() {
        return this.pluginId;
    }

    public void setPluginId( String pluginId ) {
        this.pluginId = pluginId;
    }

    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }

    public Date getLastModified() {
        return this.lastModified;
    }

    public void setLastModified( Date lastModified ) {
        this.lastModified = lastModified;
    }

    public Set getFlexfieldDataXrefs() {
        return this.flexfieldDataXrefs;
    }

    public void setFlexfieldDataXrefs( Set flexfieldDataXrefs ) {
        this.flexfieldDataXrefs = flexfieldDataXrefs;
    }
}
