/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

/**
 * FlexfieldDataXref generated by hbm2java
 */
public class FlexfieldDataXref implements java.io.Serializable {

    private String idFlexfieldDataXref;
    private PersonTable personTable;
    private FlexfieldTable flexfieldTable;
    private String objectId;
    private String objectType;
    private String data1;
    private String data2;
    private String date3;

    public FlexfieldDataXref() {
    }

    public FlexfieldDataXref(String idFlexfieldDataXref) {
        this.idFlexfieldDataXref = idFlexfieldDataXref;
    }

    public FlexfieldDataXref(String idFlexfieldDataXref, PersonTable personTable, FlexfieldTable flexfieldTable, String objectId, String objectType, String data1, String data2, String date3) {
        this.idFlexfieldDataXref = idFlexfieldDataXref;
        this.personTable = personTable;
        this.flexfieldTable = flexfieldTable;
        this.objectId = objectId;
        this.objectType = objectType;
        this.data1 = data1;
        this.data2 = data2;
        this.date3 = date3;
    }

    public String getIdFlexfieldDataXref() {
        return this.idFlexfieldDataXref;
    }

    public void setIdFlexfieldDataXref(String idFlexfieldDataXref) {
        this.idFlexfieldDataXref = idFlexfieldDataXref;
    }

    public PersonTable getPersonTable() {
        return this.personTable;
    }

    public void setPersonTable(PersonTable personTable) {
        this.personTable = personTable;
    }

    public FlexfieldTable getFlexfieldTable() {
        return this.flexfieldTable;
    }

    public void setFlexfieldTable(FlexfieldTable flexfieldTable) {
        this.flexfieldTable = flexfieldTable;
    }

    public String getObjectId() {
        return this.objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getObjectType() {
        return this.objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    public String getData1() {
        return this.data1;
    }

    public void setData1(String data1) {
        this.data1 = data1;
    }

    public String getData2() {
        return this.data2;
    }

    public void setData2(String data2) {
        this.data2 = data2;
    }

    public String getDate3() {
        return this.date3;
    }

    public void setDate3(String date3) {
        this.date3 = date3;
    }
}


