/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.clothocore.api.data.Lab;
import org.clothocore.api.data.Lab.LabDatum;
import org.clothocore.api.data.ObjBase;
import org.clothocore.api.data.ObjBase.ObjBaseDatum;
import org.clothocore.api.data.ObjType;
import org.clothocad.hibernate.hibernateDatum;

/**
 * LabTable generated by hbm2java
 */
public class LabTable implements java.io.Serializable, hibernateDatum {

    public static ObjType getType( Enum field ) {
        if ( field.getDeclaringClass() != Lab.Fields.class ) {
            return null;
        }

        Lab.Fields f = (Lab.Fields) field;

        switch ( f ) {
            case PI:
                return ObjType.PERSON;
            case INSTITUTION:
                return ObjType.INSTITUTION;
            case PERSONS:
                return ObjType.PERSON;
            default:
                return null;
        }
    }

    @Override
    public void runSecondaryProcessing(ObjBase obj) {
    }

    @Override
    public boolean needsSecondaryProcessing() {
        return false;
    }
    
    public LabTable( Lab l ) {
        this.idLab = l.getUUID();
        this.name = l.getName();
        this.dateCreated = l.getDateCreated();
        this.lastModified = l.getLastModified();
        if ( l.getPI() != null ) {
            this.personTable = new PersonTable( l.getPI().getUUID() );
        }
        if ( l.getInstitution() != null ) {
            this.institutionTable = new InstitutionTable( l.getInstitution().getUUID() );
        }
        this.department = l.getDepartment();
        this.website = l.getWebsite();
        this.address = l.getAddress();
    }

    @Override
    public ObjBase getObject() {
        Lab.LabDatum d = (LabDatum) getObjBaseDatum();
        Lab l = new Lab( d );
        return l;
    }

    @Override
    public ObjBaseDatum getObjBaseDatum() {
        String PIuuid = null, instuuid = null;
        if ( personTable != null ) {
            PIuuid = personTable.getIdPerson();
        }
        if ( institutionTable != null ) {
            instuuid = institutionTable.getIdInstitution();
        }
        Lab.LabDatum d = new Lab.LabDatum();
        d.uuid = idLab;
        d.name = name;
        d.dateCreated = dateCreated;
        d.lastModified = lastModified;
        d._address = address;
        d._department = department;
        d._website = website;
        d._principalInvestigatorUUID = PIuuid;
        d._institutionUUID = instuuid;
        return d;
    }

    @Override
    public String getUUID() {
        return idLab;
    }

    public static String translate( Enum field ) {
        if ( field.getDeclaringClass() != Lab.Fields.class ) {
            return null;
        }

        Lab.Fields f = (Lab.Fields) field;

        switch ( f ) {
            case NAME:
                return "name";
            case DATE_CREATED:
                return "dateCreated";
            case LAST_MODIFIED:
                return "lastModifed";
            case ADDRESS:
                return "address";
            case DEPARTMENT:
                return "department";
            case WEBSITE:
                return "website";
            case PI:
                return "personTable";
            case INSTITUTION:
                return "institutionTable";
            case PERSONS:
                return "personTables";
            default:
                return null;
        }

    }
    /***** AUTO-GENERATED CODE *****/
    private String idLab;
    private PersonTable personTable;
    private InstitutionTable institutionTable;
    private String name;
    private String department;
    private String website;
    private String address;
    private Date dateCreated;
    private Date lastModified;
    private Set<PersonTable> personTables = new HashSet<PersonTable>( 0 );

    public LabTable() {
    }

    public LabTable( String idLab ) {
        this.idLab = idLab;
    }

    public LabTable( String idLab, PersonTable personTable, InstitutionTable institutionTable, String name, String department, String website, String address, Date dateCreated, Date lastModified, Set personTables ) {
        this.idLab = idLab;
        this.personTable = personTable;
        this.institutionTable = institutionTable;
        this.name = name;
        this.department = department;
        this.website = website;
        this.address = address;
        this.dateCreated = dateCreated;
        this.lastModified = lastModified;
        this.personTables = personTables;
    }

    public String getIdLab() {
        return this.idLab;
    }

    public void setIdLab( String idLab ) {
        this.idLab = idLab;
    }

    public PersonTable getPersonTable() {
        return this.personTable;
    }

    public void setPersonTable( PersonTable personTable ) {
        this.personTable = personTable;
    }

    public InstitutionTable getInstitutionTable() {
        return this.institutionTable;
    }

    public void setInstitutionTable( InstitutionTable institutionTable ) {
        this.institutionTable = institutionTable;
    }

    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public String getDepartment() {
        return this.department;
    }

    public void setDepartment( String department ) {
        this.department = department;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite( String website ) {
        this.website = website;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress( String address ) {
        this.address = address;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }

    public Date getLastModified() {
        return this.lastModified;
    }

    public void setLastModified( Date lastModified ) {
        this.lastModified = lastModified;
    }

    public Set getPersonTables() {
        return this.personTables;
    }

    public void setPersonTables( Set personTables ) {
        this.personTables = personTables;
    }
}
