/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.clothocore.api.data.ObjBase;
import org.clothocore.api.data.ObjBase.ObjBaseDatum;
import org.clothocore.api.data.ObjType;
import org.clothocore.api.data.Oligo;
import org.clothocore.api.data.Oligo.OligoDatum;
import org.clothocad.hibernate.hibernateDatum;

/**
 * OligoTable generated by hbm2java
 */
public class OligoTable implements java.io.Serializable, hibernateDatum {

    public static ObjType getType( Enum field ) {
        if ( field.getDeclaringClass() != Oligo.Fields.class ) {
            return null;
        }

        Oligo.Fields f = (Oligo.Fields) field;

        switch ( f ) {
            case AUTHOR:
                return ObjType.PERSON;
            case SEQUENCE:
                return ObjType.NUCSEQ;
            default:
                return null;
        }
    }

    public OligoTable( Oligo o ) {
        this.idOligo = o.getUUID();
        this.name = o.getName();
        this.dateCreated = o.getDateCreated();
        this.lastModified = o.getLastModified();
        if ( o.getAuthor() != null ) {
            this.personTable = new PersonTable( o.getAuthor().getUUID() );
        }
        if ( o.getSeq() != null ) {
            this.nucseqTable = new NucseqTable( o.getSeq().getUUID() );
        }

        this.description = o.getDescription();
    }

    @Override
    public void runSecondaryProcessing(ObjBase obj) {
    }

    @Override
    public boolean needsSecondaryProcessing() {
        return false;
    }
    
    @Override
    public ObjBase getObject() {
        Oligo.OligoDatum d = (OligoDatum) getObjBaseDatum();
        Oligo o = new Oligo( d );
        return o;
    }

    @Override
    public ObjBaseDatum getObjBaseDatum() {
        Oligo.OligoDatum d = new Oligo.OligoDatum();
        d.uuid = idOligo;
        d.name = name;
        d.dateCreated = dateCreated;
        d.lastModified = lastModified;
        d._authorUUID = personTable.getIdPerson();
        d._seqId = nucseqTable.getIdNucseq();
        d._description = description;
        return d;
    }

    @Override
    public String getUUID() {
        return idOligo;
    }

    public static String translate( Enum field ) {
        if ( field.getDeclaringClass() != Oligo.Fields.class ) {
            return null;
        }

        Oligo.Fields f = (Oligo.Fields) field;

        switch ( f ) {
            case NAME:
                return "name";
            case DATE_CREATED:
                return "dateCreated";
            case LAST_MODIFIED:
                return "lastModifed";
            case DESCRIPTION:
                return "description";

            case AUTHOR:
                return "personTable";
            case SEQUENCE:
                return "nucseqTable";
            default:
                return null;
        }
    }
    /***** AUTO-GENERATED CODE *****/
    private String idOligo;
    private PersonTable personTable;
    private NucseqTable nucseqTable;
    private String name;
    private String description;
    private Date dateCreated;
    private Date lastModified;
    private Set sampleTables = new HashSet( 0 );

    public OligoTable() {
    }

    public OligoTable( String idOligo ) {
        this.idOligo = idOligo;
    }

    public OligoTable( String idOligo, PersonTable personTable, NucseqTable nucseqTable, String name, String description, Date dateCreated, Date lastModified, Set sampleTables ) {
        this.idOligo = idOligo;
        this.personTable = personTable;
        this.nucseqTable = nucseqTable;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
        this.lastModified = lastModified;
        this.sampleTables = sampleTables;
    }

    public String getIdOligo() {
        return this.idOligo;
    }

    public void setIdOligo( String idOligo ) {
        this.idOligo = idOligo;
    }

    public PersonTable getPersonTable() {
        return this.personTable;
    }

    public void setPersonTable( PersonTable personTable ) {
        this.personTable = personTable;
    }

    public NucseqTable getNucseqTable() {
        return this.nucseqTable;
    }

    public void setNucseqTable( NucseqTable nucseqTable ) {
        this.nucseqTable = nucseqTable;
    }

    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription( String description ) {
        this.description = description;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }

    public Date getLastModified() {
        return this.lastModified;
    }

    public void setLastModified( Date lastModified ) {
        this.lastModified = lastModified;
    }

    public Set getSampleTables() {
        return this.sampleTables;
    }

    public void setSampleTables( Set sampleTables ) {
        this.sampleTables = sampleTables;
    }
}
