/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PartGrammarXref generated by hbm2java
 */
public class PartGrammarXref  implements java.io.Serializable {


     private PartGrammarXrefId id;
     private GrammarTable grammarTable;
     private PersonTable personTable;
     private PartTable partTable;
     private String token;
     private Date dateCreated;
     private Date lastModified;

    public PartGrammarXref() {
    }

	
    public PartGrammarXref(PartGrammarXrefId id, GrammarTable grammarTable, PartTable partTable) {
        this.id = id;
        this.grammarTable = grammarTable;
        this.partTable = partTable;
    }
    public PartGrammarXref(PartGrammarXrefId id, GrammarTable grammarTable, PersonTable personTable, PartTable partTable, String token, Date dateCreated, Date lastModified) {
       this.id = id;
       this.grammarTable = grammarTable;
       this.personTable = personTable;
       this.partTable = partTable;
       this.token = token;
       this.dateCreated = dateCreated;
       this.lastModified = lastModified;
    }
   
    public PartGrammarXrefId getId() {
        return this.id;
    }
    
    public void setId(PartGrammarXrefId id) {
        this.id = id;
    }
    public GrammarTable getGrammarTable() {
        return this.grammarTable;
    }
    
    public void setGrammarTable(GrammarTable grammarTable) {
        this.grammarTable = grammarTable;
    }
    public PersonTable getPersonTable() {
        return this.personTable;
    }
    
    public void setPersonTable(PersonTable personTable) {
        this.personTable = personTable;
    }
    public PartTable getPartTable() {
        return this.partTable;
    }
    
    public void setPartTable(PartTable partTable) {
        this.partTable = partTable;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


