package org.clothocad.hibernate.data;
// Generated Jul 28, 2010 6:07:49 PM by Hibernate Tools 3.2.1.GA



/**
 * StrainPlasmidXrefId generated by hbm2java
 */
public class StrainPlasmidXrefId  implements java.io.Serializable {


     private String strainId;
     private String plasmidId;

    public StrainPlasmidXrefId() {
    }

    public StrainPlasmidXrefId(String strainId, String plasmidId) {
       this.strainId = strainId;
       this.plasmidId = plasmidId;
    }
   
    public String getStrainId() {
        return this.strainId;
    }
    
    public void setStrainId(String strainId) {
        this.strainId = strainId;
    }
    public String getPlasmidId() {
        return this.plasmidId;
    }
    
    public void setPlasmidId(String plasmidId) {
        this.plasmidId = plasmidId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StrainPlasmidXrefId) ) return false;
		 StrainPlasmidXrefId castOther = ( StrainPlasmidXrefId ) other; 
         
		 return ( (this.getStrainId()==castOther.getStrainId()) || ( this.getStrainId()!=null && castOther.getStrainId()!=null && this.getStrainId().equals(castOther.getStrainId()) ) )
 && ( (this.getPlasmidId()==castOther.getPlasmidId()) || ( this.getPlasmidId()!=null && castOther.getPlasmidId()!=null && this.getPlasmidId().equals(castOther.getPlasmidId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStrainId() == null ? 0 : this.getStrainId().hashCode() );
         result = 37 * result + ( getPlasmidId() == null ? 0 : this.getPlasmidId().hashCode() );
         return result;
   }   


}


