package org.clothocad.hibernate.data;
// Generated Oct 12, 2010 7:14:51 PM by Hibernate Tools 3.2.1.GA



/**
 * TraitFamilyXrefId generated by hbm2java
 */
public class TraitFamilyXrefId  implements java.io.Serializable {


     private String traitId;
     private String familyId;

    public TraitFamilyXrefId() {
    }

    public TraitFamilyXrefId(String traitId, String familyId) {
       this.traitId = traitId;
       this.familyId = familyId;
    }
   
    public String getTraitId() {
        return this.traitId;
    }
    
    public void setTraitId(String traitId) {
        this.traitId = traitId;
    }
    public String getFamilyId() {
        return this.familyId;
    }
    
    public void setFamilyId(String familyId) {
        this.familyId = familyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TraitFamilyXrefId) ) return false;
		 TraitFamilyXrefId castOther = ( TraitFamilyXrefId ) other; 
         
		 return ( (this.getTraitId()==castOther.getTraitId()) || ( this.getTraitId()!=null && castOther.getTraitId()!=null && this.getTraitId().equals(castOther.getTraitId()) ) )
 && ( (this.getFamilyId()==castOther.getFamilyId()) || ( this.getFamilyId()!=null && castOther.getFamilyId()!=null && this.getFamilyId().equals(castOther.getFamilyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTraitId() == null ? 0 : this.getTraitId().hashCode() );
         result = 37 * result + ( getFamilyId() == null ? 0 : this.getFamilyId().hashCode() );
         return result;
   }   


}


