/*
 Copyright (c) 2009 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * CollectionXref generated by hbm2java
 */
public class Collectionxref implements java.io.Serializable {

    /***** AUTO-GENERATED CODE *****/
    private CollectionxrefId id;
    private CollectionTable collectionTable;
    private PersonTable personTable;
    private String objectType;
    private Date dateCreated;
    private Date lastmodified;

    public Collectionxref() {
    }

    public Collectionxref(CollectionxrefId id, CollectionTable collectionTable) {
        this.id = id;
        this.collectionTable = collectionTable;
    }

    public Collectionxref(CollectionxrefId id, CollectionTable collectionTable, PersonTable personTable, String objectType, Date dateCreated, Date lastmodified) {
        this.id = id;
        this.collectionTable = collectionTable;
        this.personTable = personTable;
        this.objectType = objectType;
        this.dateCreated = dateCreated;
        this.lastmodified = lastmodified;
    }

    public CollectionxrefId getId() {
        return this.id;
    }

    public void setId(CollectionxrefId id) {
        this.id = id;
    }

    public CollectionTable getCollectionTable() {
        return this.collectionTable;
    }

    public void setCollectionTable(CollectionTable collectionTable) {
        this.collectionTable = collectionTable;
    }

    public PersonTable getPersonTable() {
        return this.personTable;
    }

    public void setPersonTable(PersonTable personTable) {
        this.personTable = personTable;
    }

    public String getObjectType() {
        return this.objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getLastmodified() {
        return this.lastmodified;
    }

    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }
}


