package org.clothocad.hibernate.data;
// Generated Oct 12, 2010 7:14:51 PM by Hibernate Tools 3.2.1.GA



/**
 * FeatureFamilyXrefId generated by hbm2java
 */
public class FeatureFamilyXrefId  implements java.io.Serializable {


     private String familyId;
     private String featureId;

    public FeatureFamilyXrefId() {
    }

    public FeatureFamilyXrefId(String familyId, String featureId) {
       this.familyId = familyId;
       this.featureId = featureId;
    }
   
    public String getFamilyId() {
        return this.familyId;
    }
    
    public void setFamilyId(String familyId) {
        this.familyId = familyId;
    }
    public String getFeatureId() {
        return this.featureId;
    }
    
    public void setFeatureId(String featureId) {
        this.featureId = featureId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FeatureFamilyXrefId) ) return false;
		 FeatureFamilyXrefId castOther = ( FeatureFamilyXrefId ) other; 
         
		 return ( (this.getFamilyId()==castOther.getFamilyId()) || ( this.getFamilyId()!=null && castOther.getFamilyId()!=null && this.getFamilyId().equals(castOther.getFamilyId()) ) )
 && ( (this.getFeatureId()==castOther.getFeatureId()) || ( this.getFeatureId()!=null && castOther.getFeatureId()!=null && this.getFeatureId().equals(castOther.getFeatureId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFamilyId() == null ? 0 : this.getFamilyId().hashCode() );
         result = 37 * result + ( getFeatureId() == null ? 0 : this.getFeatureId().hashCode() );
         return result;
   }   


}


