package org.clothocad.hibernate.data;
// Generated Jul 26, 2010 11:53:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * FeatureNoteXref generated by hbm2java
 */
public class FeatureNoteXref  implements java.io.Serializable {


     private FeatureNoteXrefId id;
     private FeatureTable featureTable;
     private NoteTable noteTable;
     private Date lastModified;
     private Date dateCreated;

    public FeatureNoteXref() {
    }

	
    public FeatureNoteXref(FeatureNoteXrefId id, FeatureTable featureTable, NoteTable noteTable) {
        this.id = id;
        this.featureTable = featureTable;
        this.noteTable = noteTable;

        //JCA added this:
       this.dateCreated = new Date();
       this.lastModified = new Date();
    }
    public FeatureNoteXref(FeatureNoteXrefId id, FeatureTable featureTable, NoteTable noteTable, Date lastModified, Date dateCreated) {
       this.id = id;
       this.featureTable = featureTable;
       this.noteTable = noteTable;
       this.lastModified = lastModified;
       this.dateCreated = dateCreated;
    }
   
    public FeatureNoteXrefId getId() {
        return this.id;
    }
    
    public void setId(FeatureNoteXrefId id) {
        this.id = id;
    }
    public FeatureTable getFeatureTable() {
        return this.featureTable;
    }
    
    public void setFeatureTable(FeatureTable featureTable) {
        this.featureTable = featureTable;
    }
    public NoteTable getNoteTable() {
        return this.noteTable;
    }
    
    public void setNoteTable(NoteTable noteTable) {
        this.noteTable = noteTable;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


