/*
Copyright (c) 2009 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS..
 */
package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.clothocore.api.data.Grammar;
import org.clothocore.api.data.Grammar.GrammarDatum;
import org.clothocore.api.data.ObjBase;
import org.clothocore.api.data.ObjBase.ObjBaseDatum;
import org.clothocore.api.data.ObjType;
import org.clothocad.hibernate.hibernateDatum;

/**
 * GrammarTable generated by hbm2java
 */
public class GrammarTable implements java.io.Serializable, hibernateDatum {

    public static ObjType getType( Enum field ) {
        return null;
    }

    public GrammarTable( Grammar f ) {
        this.idGrammar = f.getUUID();
        this.name = f.getName();
        this.description = f.getShortDescription();
        this.dateCreated = f.getDateCreated();
        this.lastModified = f.getLastModified();
        this.pluginDownloadLink = f.getPluginDownloadLink();
        this.pluginHelpLink = f.getPluginHelpLink();
        this.pluginId = f.getPluginId();
        // TODO: setup vector, part, and plasmid tables
    }

    @Override
    public ObjBase getObject() {
        Grammar.GrammarDatum d = (GrammarDatum) getObjBaseDatum();
        Grammar f = new Grammar( d );
        return f;
    }

    @Override
    public void runSecondaryProcessing(ObjBase obj) {
    }

    @Override
    public boolean needsSecondaryProcessing() {
        return false;
    }

    @Override
    public ObjBaseDatum getObjBaseDatum() {
        Grammar.GrammarDatum d = new Grammar.GrammarDatum();
        d.uuid = idGrammar;
        d.name = name;
        d.dateCreated = dateCreated;
        d.lastModified = lastModified;
        d._shortDescription = description;
        d._pluginDownloadLink = pluginDownloadLink;
        d._pluginHelpLink = pluginHelpLink;
        d._pluginId = pluginId;
        return d;
    }

    @Override
    public String getUUID() {
        return idGrammar;
    }

    public static String translate( Enum field ) {
        if ( field.getDeclaringClass() != Grammar.Fields.class ) {
            return null;
        }

        Grammar.Fields f = (Grammar.Fields) field;

        switch ( f ) {
            case NAME:
                return "name";
            case DATE_CREATED:
                return "dateCreated";
            case LAST_MODIFIED:
                return "lastModifed";
            case DOWNLOAD_LINK:
                return "pluginDownloadLink";
            case HELP_LINK:
                return "pluginHelpLink";
            case LONG_DESCRIPTION:
                return "description";
            case SHORT_DESCRIPTION:
                return "description";
            case PLUGIN_ID:
                return "pluginId";
            default:
                return null;
        }
    }
    /***** AUTO-GENERATED CODE *****/
    private String idGrammar;
    private String name;
    private String pluginHelpLink;
    private String pluginDownloadLink;
    private String description;
    private String pluginId;
    private Date dateCreated;
    private Date lastModified;
    private Set partGrammarXrefs = new HashSet( 0 );

    public GrammarTable() {
    }

    public GrammarTable( String idGrammar ) {
        this.idGrammar = idGrammar;
    }

    public GrammarTable( String idGrammar, String name, String pluginHelpLink, String pluginDownloadLink, String description, String pluginId, Date dateCreated, Date lastModified, Set partGrammarXrefs ) {
        this.idGrammar = idGrammar;
        this.name = name;
        this.pluginHelpLink = pluginHelpLink;
        this.pluginDownloadLink = pluginDownloadLink;
        this.description = description;
        this.pluginId = pluginId;
        this.dateCreated = dateCreated;
        this.lastModified = lastModified;
        this.partGrammarXrefs = partGrammarXrefs;
    }

    public String getIdGrammar() {
        return this.idGrammar;
    }

    public void setIdGrammar( String idGrammar ) {
        this.idGrammar = idGrammar;
    }

    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public String getPluginHelpLink() {
        return this.pluginHelpLink;
    }

    public void setPluginHelpLink( String pluginHelpLink ) {
        this.pluginHelpLink = pluginHelpLink;
    }

    public String getPluginDownloadLink() {
        return this.pluginDownloadLink;
    }

    public void setPluginDownloadLink( String pluginDownloadLink ) {
        this.pluginDownloadLink = pluginDownloadLink;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription( String description ) {
        this.description = description;
    }

    public String getPluginId() {
        return this.pluginId;
    }

    public void setPluginId( String pluginId ) {
        this.pluginId = pluginId;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated( Date dateCreated ) {
        this.dateCreated = dateCreated;
    }

    public Date getLastModified() {
        return this.lastModified;
    }

    public void setLastModified( Date lastModified ) {
        this.lastModified = lastModified;
    }

    public Set getPartGrammarXrefs() {
        return this.partGrammarXrefs;
    }

    public void setPartGrammarXrefs( Set partGrammarXrefs ) {
        this.partGrammarXrefs = partGrammarXrefs;
    }
}
