package org.clothocad.hibernate.data;
// Generated Jun 1, 2010 8:47:54 PM by Hibernate Tools 3.2.1.GA



/**
 * PartGrammarXrefId generated by hbm2java
 */
public class PartGrammarXrefId  implements java.io.Serializable {


     private String partId;
     private String grammarId;

    public PartGrammarXrefId() {
    }

    public PartGrammarXrefId(String partId, String grammarId) {
       this.partId = partId;
       this.grammarId = grammarId;
    }
   
    public String getPartId() {
        return this.partId;
    }
    
    public void setPartId(String partId) {
        this.partId = partId;
    }
    public String getGrammarId() {
        return this.grammarId;
    }
    
    public void setGrammarId(String grammarId) {
        this.grammarId = grammarId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartGrammarXrefId) ) return false;
		 PartGrammarXrefId castOther = ( PartGrammarXrefId ) other; 
         
		 return ( (this.getPartId()==castOther.getPartId()) || ( this.getPartId()!=null && castOther.getPartId()!=null && this.getPartId().equals(castOther.getPartId()) ) )
 && ( (this.getGrammarId()==castOther.getGrammarId()) || ( this.getGrammarId()!=null && castOther.getGrammarId()!=null && this.getGrammarId().equals(castOther.getGrammarId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPartId() == null ? 0 : this.getPartId().hashCode() );
         result = 37 * result + ( getGrammarId() == null ? 0 : this.getGrammarId().hashCode() );
         return result;
   }   


}


