package org.clothocad.hibernate.data;
// Generated Jul 28, 2010 6:07:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StrainPlasmidXref generated by hbm2java
 */
public class StrainPlasmidXref  implements java.io.Serializable {


     private StrainPlasmidXrefId id;
     private PersonTable personTable;
     private PlasmidTable plasmidTable;
     private StrainTable strainTable;
     private Integer genomeStart;
     private Integer genomeEnd;
     private Boolean revComp;
     private Boolean isGenomic;
     private Date dateCreated;
     private Date lastModified;

    public StrainPlasmidXref() {
    }


    public StrainPlasmidXref(StrainPlasmidXrefId id, PlasmidTable plasmidTable, StrainTable strainTable) {
        this.id = id;
        this.plasmidTable = plasmidTable;
        this.strainTable = strainTable;

        //JCA added these:
       this.dateCreated = new Date();
       this.lastModified = new Date();
    }
    public StrainPlasmidXref(StrainPlasmidXrefId id, PersonTable personTable, PlasmidTable plasmidTable, StrainTable strainTable, Integer genomeStart, Integer genomeEnd, Boolean revComp, Boolean isGenomic, Date dateCreated, Date lastModified) {
       this.id = id;
       this.personTable = personTable;
       this.plasmidTable = plasmidTable;
       this.strainTable = strainTable;
       this.genomeStart = genomeStart;
       this.genomeEnd = genomeEnd;
       this.revComp = revComp;
       this.isGenomic = isGenomic;
       this.dateCreated = dateCreated;
       this.lastModified = lastModified;
    }

    public StrainPlasmidXrefId getId() {
        return this.id;
    }

    public void setId(StrainPlasmidXrefId id) {
        this.id = id;
    }
    public PersonTable getPersonTable() {
        return this.personTable;
    }

    public void setPersonTable(PersonTable personTable) {
        this.personTable = personTable;
    }
    public PlasmidTable getPlasmidTable() {
        return this.plasmidTable;
    }

    public void setPlasmidTable(PlasmidTable plasmidTable) {
        this.plasmidTable = plasmidTable;
    }
    public StrainTable getStrainTable() {
        return this.strainTable;
    }

    public void setStrainTable(StrainTable strainTable) {
        this.strainTable = strainTable;
    }
    public Integer getGenomeStart() {
        return this.genomeStart;
    }

    public void setGenomeStart(Integer genomeStart) {
        this.genomeStart = genomeStart;
    }
    public Integer getGenomeEnd() {
        return this.genomeEnd;
    }

    public void setGenomeEnd(Integer genomeEnd) {
        this.genomeEnd = genomeEnd;
    }
    public Boolean getRevComp() {
        return this.revComp;
    }

    public void setRevComp(Boolean revComp) {
        this.revComp = revComp;
    }
    public Boolean getIsGenomic() {
        return this.isGenomic;
    }

    public void setIsGenomic(Boolean isGenomic) {
        this.isGenomic = isGenomic;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getLastModified() {
        return this.lastModified;
    }

    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


