/*
 * File: TextViewerWindow.ui.js
 * Date: Mon Nov 15 2010 00:45:53 GMT-0800 (PST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

TextViewerWindowUi = Ext.extend(Ext.Window, {
    title: 'Text Viewer',
    width: 800,
    height: 600,
    layout: 'fit',
    maximizable: true,
    initComponent: function() {
        TextViewerWindowUi.superclass.initComponent.call(this);
    }
});
